version: "3.9"


services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
     - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress                                    
    image: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - wp_admin_passwd
      - wp_user_passwd
      - db_user_passwd
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_root_passwd
      - db_user_passwd
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device:  /home/${USER}/data/wp
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${USER}/data/db
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge

secrets:
  wp_user_passwd:
    file: ../secrets/wp_user_passwd.txt
  wp_admin_passwd:
    file: ../secrets/wp_admin_passwd.txt
  db_root_passwd:
    file : ../secrets/db_root_passwd.txt
  db_user_passwd:
    file: ../secrets/db_user_passwd.txt