version: "3.5"


services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    image: ng-image
    ports:
     - "443:443"
    volumes:
      - wordpress:/var/www/html 
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - wp_user_passwd
    restart: always
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress                                             
    image: wp-image
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - wp_user_passwd
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mdb-image
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - wp_user_passwd
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device:  /home/${USER}/data/wp
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${USER}/data/db
      o: bind
      type: none

networks:
  inception:
    name: inception

secrets:
   wp_user_passwd:
     file: wp_user_passwd.txt